# Site settings
short_title: Orcas
title: Orcas - Automatisches Deployment für die Datenbank
description: >
 Orcas ist ein Open Source Deploymentframework mit dem ein bestehendes Datenbankschema in einen in Orcas
 beschriebenen Soll-Zustand geführt werden kann. Orcas steht für Oracle adaptive/agile schemas und
 ist nur mit Oracle RDBMS kompatibel.

# Twitter
twitter:
  username: OC_WIRE

# GitHub (required for local site builds)
github:
  owner_name: opitzconsulting
  repository_name: orcas
  repository_url: https://github.com/opitzconsulting/orcas

# Build settings
baseurl: /orcas
permalink: docs/:title
markdown: kramdown
highlighter: pygments
relative_permalinks: false
collections:
  docs:
    output: true
