# Site settings
title: Orcas
subtitle: "- Oracle adaptive/agile schemas"
#email: your-email@domain.com
description: > 
 Orcas ist ein Deploymentframework mit dem ein bestehendes Datenbankschema in einen in Orcas 
 beschriebenen Soll-Zustand geführt werden kann. Orcas steht für Oracle adaptive/agile schemas und 
 ist nur mit Oracle RDBMS kompatibel.
baseurl: "/orcas" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: OC_WIRE
github_username:  opitzconsulting/Orcas

# Build settings
markdown: kramdown
